##### exemplo

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-deploy
  name: game-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-deploy
  template:
    metadata:
      labels:
        app: game-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80