##### exemplo

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris
  name: tetris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - image: bsord/tetris
        name: tetris
        ports:
        - containerPort: 80