##### exemplo
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tetris
  name: service-tetris
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tetris
  type: LoadBalancer